# Generated by Django 4.0.5 on 2022-07-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='senors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flame1', models.CharField(blank=True, max_length=16)),
                ('flame2', models.CharField(blank=True, max_length=16)),
                ('flame3', models.CharField(blank=True, max_length=16)),
                ('flame4', models.CharField(blank=True, max_length=16)),
                ('flame5', models.CharField(blank=True, max_length=16)),
                ('flame6', models.CharField(blank=True, max_length=16)),
                ('flame7', models.CharField(blank=True, max_length=16)),
                ('flame8', models.CharField(blank=True, max_length=16)),
                ('smoke1', models.CharField(blank=True, max_length=16)),
                ('smoke2', models.CharField(blank=True, max_length=16)),
                ('smoke3', models.CharField(blank=True, max_length=16)),
                ('smoke4', models.CharField(blank=True, max_length=16)),
                ('smoke5', models.CharField(blank=True, max_length=16)),
                ('smoke6', models.CharField(blank=True, max_length=16)),
                ('smoke7', models.CharField(blank=True, max_length=16)),
                ('smoke8', models.CharField(blank=True, max_length=16)),
                ('motion', models.CharField(blank=True, max_length=16)),
                ('humidity', models.CharField(blank=True, max_length=16)),
                ('temperature1', models.CharField(blank=True, max_length=16)),
                ('temperature2', models.CharField(blank=True, max_length=16)),
                ('water', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
