# Generated by Django 3.2.14 on 2022-07-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensors_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(blank=True, max_length=32)),
                ('value', models.CharField(max_length=16, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
